### ISSUE TITLE
Corrigir quebra de palavras longas nas postagens

### ISSUE THREAD

**Issue by douglasjunior** [douglasjunior/Facebug#12]
Como está atualmente:
![errado1](https://cloud.githubusercontent.com/assets/1512341/7601770/5bfa8008-f8f1-11e4-8266-75971239c77b.PNG)

Como deveria ser:
![correto1](https://cloud.githubusercontent.com/assets/1512341/7601775/681b5bd2-f8f1-11e4-81fe-9a84e58243c6.PNG)

**Comment by douglasjunior** [comment]
@douglassikeira

**Comment by douglasjunior** [comment]
@misaelrodrigo

**Comment by misaelrodrigo** [comment]
@douglasjunior tenho que resolver também esse problema?
![bug](https://cloud.githubusercontent.com/assets/9470369/7902018/f423bedc-077c-11e5-934d-12b7e081ae8e.png)

**Comment by douglasjunior** [comment]
Para o exercício não precisa, mas se quiser fique a vontade.
