### ISSUE TITLE
Postagem não exibe quebra de linha.

### ISSUE THREAD

**Issue by douglasjunior** [douglasjunior/Facebug#13]
A postagem é criada com quebras de linhas, porém na exibição elas não aparecem:
![postagem nao exibe quebra de linha](https://cloud.githubusercontent.com/assets/1512341/7623526/81ab52bc-f9b1-11e4-95ec-254ec0c1fbdb.PNG)

**Comment by douglasjunior** [comment]
@dorga

**Comment by GustavoMantuan** [comment]
Professor, mandei meu pull request, chegou ai?

**Comment by douglasjunior** [comment]
Não, rsrsrsrs

Só tem um do @feelipegr que vou olhar depois.

https://github.com/douglasjunior/Facebug/pulls

**Comment by douglasjunior** [comment]
@GustavoMantuan, a implementação deu certo, porém tem alguns casos que precisamos de uma verificação extra.

Por exemplo, quando a postagem é carregada para Edição, não pode substituir `\n` por `<br />`, se não fica assim:
![captura de tela 2015-05-18 as 08 55 15](https://cloud.githubusercontent.com/assets/1512341/7680341/e411b58a-fd3b-11e4-9449-17c9e50593ba.png)

Talvez seria interessante adicionar um parâmetro `true/false` no método para dizer se substitui a quebra de linha ou não. E também pode manter uma declaração deste método sem o `true/false` que sempre substitui a quebra.
