### ISSUE TITLE
Criar página de erro personalizada

### ISSUE THREAD

**Issue by douglasjunior** [douglasjunior/Facebug#14]
Criar e configurar uma página de erro padrão, para evitar que seja exibida a página de erros do tomcat:

![captura de tela 2015-05-14 as 08 45 55](https://cloud.githubusercontent.com/assets/1512341/7631251/e10d28c0-fa15-11e4-88da-520f990e16d9.png)

**Comment by douglasjunior** [comment]
Jucemar

**Comment by douglasjunior** [comment]
@brunomartinsdossantos

**Comment by BrunoMartinsdosSantos** [comment]
.
