### ISSUE TITLE
Fazer validação de XSS

### ISSUE THREAD

**Issue by douglasjunior** [douglasjunior/Facebug#2]
É preciso fazer validação de XSS nos campos de texto, para evitar que o usuário injete código HTML, CSS ou JAVASCRIPT.

Saiva mais: http://www.redesegura.com.br/2012/01/saiba-mais-sobre-o-cross-site-scripting-xss/

**Comment by douglasjunior** [comment]
@feelipegr

**Comment by douglasjunior** [comment]
###### ~~Dica: Verifique a página 24 do slide 14~~

**Comment by douglasjunior** [comment]
@feelipegr tem alguns lugares que você esqueceu de validar, como no include do `topo.jsp`. Verifique todas as páginas que imprimem String, você pode buscar por `<%= %>`. E também no preenchimento dos `input` dos formulários.

**Comment by feelipegr** [comment]
@douglasjunior está corrigido em https://github.com/douglasjunior/Facebug/pull/18
