### ISSUE TITLE
Fazer validação para não postar "em branco"

### ISSUE THREAD

**Issue by feelipegr** [douglasjunior/Facebug#5]
Fazer validação para não fazer o post quando o texto estiver vazio.

**Comment by GustavoMantuan** [comment]
Acho que  edevaldo já resolveu isso! #3

**Comment by feelipegr** [comment]
Ah, verdade, quando testei ainda tava com o bug e não tinha visto, vlw =)

**Comment by douglasjunior** [comment]
O @edvaldoszy está implementado em #3.
